# Dataproc Cluster Configuration — NYC Taxi Trips Project
# Cluster: cluster-c814 | Region: us-central1 | Project: project-bac9f556-1ccf-44de-801

clusterName: cluster-c814
projectId: project-bac9f556-1ccf-44de-801

config:
  clusterTier: CLUSTER_TIER_STANDARD

  masterConfig:
    numInstances: 1
    machineTypeUri: n4-standard-2
    diskConfig:
      bootDiskType: hyperdisk-balanced
      bootDiskSizeGb: 100

  workerConfig:
    numInstances: 2
    machineTypeUri: n4-standard-2
    diskConfig:
      bootDiskType: hyperdisk-balanced
      bootDiskSizeGb: 200

  softwareConfig:
    imageVersion: 2.2.71-debian12
    optionalComponents:
      - JUPYTER
    properties:
      spark:spark.executor.instances: '2'
      spark:spark.executor.cores: '1'
      spark:spark.executor.memory: 2893m
      spark:spark.driver.memory: 2048m
      yarn:yarn.nodemanager.resource.cpu-vcores: '2'
      yarn:yarn.nodemanager.resource.memory-mb: '6554'

  gceClusterConfig:
    zoneUri: us-central1-c
